// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChrkLRCyQFfXzTf2dlh4ZX1ChGXv3eqQc',
    appId: '1:267995479108:web:c3965d4b15fba67f92d011',
    messagingSenderId: '267995479108',
    projectId: 'project-nova1',
    authDomain: 'project-nova1.firebaseapp.com',
    storageBucket: 'project-nova1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkQsCJXbhbdgVRwZIiQsr3DXcLKj0nVU',
    appId: '1:267995479108:android:8c0f89e98112dfb492d011',
    messagingSenderId: '267995479108',
    projectId: 'project-nova1',
    storageBucket: 'project-nova1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMuzStptWv6buYKuksp7vBheD0pt-y1dw',
    appId: '1:267995479108:ios:af4f6581f3eba8b392d011',
    messagingSenderId: '267995479108',
    projectId: 'project-nova1',
    storageBucket: 'project-nova1.firebasestorage.app',
    iosClientId: '267995479108-4cg6becrhmcp099n6i3qhip4t46est25.apps.googleusercontent.com',
    iosBundleId: 'com.example.financials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMuzStptWv6buYKuksp7vBheD0pt-y1dw',
    appId: '1:267995479108:ios:af4f6581f3eba8b392d011',
    messagingSenderId: '267995479108',
    projectId: 'project-nova1',
    storageBucket: 'project-nova1.firebasestorage.app',
    iosClientId: '267995479108-4cg6becrhmcp099n6i3qhip4t46est25.apps.googleusercontent.com',
    iosBundleId: 'com.example.financials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChrkLRCyQFfXzTf2dlh4ZX1ChGXv3eqQc',
    appId: '1:267995479108:web:ec2315f70419295b92d011',
    messagingSenderId: '267995479108',
    projectId: 'project-nova1',
    authDomain: 'project-nova1.firebaseapp.com',
    storageBucket: 'project-nova1.firebasestorage.app',
  );
}
